In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [4]:
channel=pd.read_csv("../data/raw_data/dim_channel.csv")
date=pd.read_csv("../data/raw_data/dim_date_updated.csv")
market=pd.read_csv("../data/raw_data/dim_market.csv")
worker=pd.read_csv("../data/raw_data/dim_worker.csv")
transactions=pd.read_csv("../data/raw_data/fact_transactions_Updated_.csv")

DATA CLEANING OF RAW DATAS

In [10]:
print(channel.head())

  channel_id     channel_type       channel_subtype  is_digital  \
0      val_0  API/Third-Party          Merchant POS        True
1      val_1              POS   USSD Agent Assisted        True
2      val_2              POS       API Integration        True
3      val_3            Agent  Human Agent (Branch)        True
4      val_4              POS       API Integration       False

   avg_fraud_rate  requires_internet
0      857.610585               True
1      624.746093              False
2      559.808651              False
3      509.099903              False
4      689.533128               True

In [5]:
print(channel.dtypes)

channel_id               str
channel_type             str
channel_subtype          str
is_digital              bool
avg_fraud_rate       float64
requires_internet       bool
dtype: object

In [6]:
print(channel.isnull().sum())

channel_id           0
channel_type         0
channel_subtype      0
is_digital           0
avg_fraud_rate       0
requires_internet    0
dtype: int64

In [8]:
print(channel['channel_id'].duplicated().sum())

0

In [9]:
print(channel.duplicated().sum())

0

In [13]:
print(date.head())

    date_id full_date  year    month quarter day_of_week  is_weekend  \
0  20230101  1/1/2023  2023  January      Q1      Sunday        True
1  20230102  1/2/2023  2023  January      Q1      Monday       False
2  20230103  1/3/2023  2023  January      Q1     Tuesday       False
3  20230104  1/4/2023  2023  January      Q1   Wednesday       False
4  20230105  1/5/2023  2023  January      Q1    Thursday       False

   is_month_end  week_number
0         False          NaN
1         False          NaN
2         False          NaN
3         False          NaN
4         False          NaN

In [11]:
print(date.dtypes)

date_id           int64
full_date           str
year              int64
month               str
quarter             str
day_of_week         str
is_weekend         bool
is_month_end       bool
week_number     float64
dtype: object

In [18]:
date['full_date']=pd.to_datetime(date['full_date'])

In [19]:
date['week_number'] = date['full_date'].dt.isocalendar().week

In [101]:
date.dtypes

date_id                  int64
full_date       datetime64[us]
year                     int64
month                      str
quarter                    str
day_of_week                str
is_weekend                bool
is_month_end              bool
week_number             UInt32
dtype: object

In [12]:
print(date.isnull().sum())

date_id           0
full_date         0
year              0
month             0
quarter           0
day_of_week       0
is_weekend        0
is_month_end      0
week_number     731
dtype: int64

In [14]:
print(date['date_id'].duplicated().sum())

0

In [15]:
print(date.duplicated().sum())

0

In [21]:
print(date.head(20))

     date_id  full_date  year    month quarter day_of_week  is_weekend  \
0   20230101 2023-01-01  2023  January      Q1      Sunday        True
1   20230102 2023-01-02  2023  January      Q1      Monday       False
2   20230103 2023-01-03  2023  January      Q1     Tuesday       False
3   20230104 2023-01-04  2023  January      Q1   Wednesday       False
4   20230105 2023-01-05  2023  January      Q1    Thursday       False
5   20230106 2023-01-06  2023  January      Q1      Friday       False
6   20230107 2023-01-07  2023  January      Q1    Saturday        True
7   20230108 2023-01-08  2023  January      Q1      Sunday        True
8   20230109 2023-01-09  2023  January      Q1      Monday       False
9   20230110 2023-01-10  2023  January      Q1     Tuesday       False
10  20230111 2023-01-11  2023  January      Q1   Wednesday       False
11  20230112 2023-01-12  2023  January      Q1    Thursday       False
12  20230113 2023-01-13  2023  January      Q1      Friday       False
13  20230114 2023-01-14  2023  January      Q1    Saturday        True
14  20230115 2023-01-15  2023  January      Q1      Sunday        True
15  20230116 2023-01-16  2023  January      Q1      Monday       False
16  20230117 2023-01-17  2023  January      Q1     Tuesday       False
17  20230118 2023-01-18  2023  January      Q1   Wednesday       False
18  20230119 2023-01-19  2023  January      Q1    Thursday       False
19  20230120 2023-01-20  2023  January      Q1      Friday       False

    is_month_end  week_number
0          False           52
1          False            1
2          False            1
3          False            1
4          False            1
5          False            1
6          False            1
7          False            1
8          False            2
9          False            2
10         False            2
11         False            2
12         False            2
13         False            2
14         False            2
15         False            3
16         False            3
17         False            3
18         False            3
19         False            3

In [78]:
date.to_csv('../data/clean_data/dim_date_updated_cleaned.csv',index=False)

In [23]:
print(market.head())

  market_id       country iso_code local_currency    dominant_channel  \
0     val_0       Nigeria       NG            NGN  Mobile Money Agent
1     val_1         Kenya       KE            KES          Mobile App
2     val_2         Ghana       GH            GHS       Bank Transfer
3     val_3  South Africa       ZA            ZAR  Mobile Money Agent

     regulatory_tier  usd_fx_rate  market_fraud_index
0  Emerging (Tier 3)    80.233076          392.846248
1    Mature (Tier 1)   366.077978          267.522034
2    Mature (Tier 1)   872.420701          421.603210
3    Mature (Tier 1)   354.436281          797.512131

In [25]:
market.dtypes

market_id                 str
country                   str
iso_code                  str
local_currency            str
dominant_channel          str
regulatory_tier           str
usd_fx_rate           float64
market_fraud_index    float64
dtype: object

In [27]:
market.isnull().sum()

market_id             0
country               0
iso_code              0
local_currency        0
dominant_channel      0
regulatory_tier       0
usd_fx_rate           0
market_fraud_index    0
dtype: int64

In [29]:
market.duplicated().sum()

np.int64(0)

In [30]:
market['market_id'].duplicated().sum()

np.int64(0)

In [31]:
worker.head()

,worker_id,worker_name,gig_segment,account_tenure_days,kyc_tier,gender,age_band,risk_score,is_active,preferred_channel
0,val_0,Ngozi Eze,Delivery Rider,618,Tier 0 (Unverified),Male,55+,34.755498,False,Web
1,val_1,Sipho Dlamini,Ride-Hailing Driver,398,Tier 2 (ID Verified),Non-Binary,45-54,10.280724,False,Agent
2,val_2,Nana Adjei,On-Demand Handyman,950,Tier 2 (ID Verified),Male,35-44,30.206847,True,Web
3,val_3,Mary Wairimu,Agricultural Day Labourer,1210,Tier 2 (ID Verified),Non-Binary,18-24,80.670635,False,Mobile App (Android)
4,val_4,Mary Wairimu,Informal Vendor,477,Tier 2 (ID Verified),Non-Binary,18-24,49.347953,False,Mobile App (Android)

In [32]:
worker.dtypes

worker_id                  str
worker_name                str
gig_segment                str
account_tenure_days      int64
kyc_tier                   str
gender                     str
age_band                   str
risk_score             float64
is_active                 bool
preferred_channel          str
dtype: object

In [33]:
worker.isnull().sum()

worker_id              0
worker_name            0
gig_segment            0
account_tenure_days    0
kyc_tier               0
gender                 0
age_band               0
risk_score             0
is_active              0
preferred_channel      0
dtype: int64

In [34]:
worker.duplicated().sum()

np.int64(0)

In [35]:
worker['worker_id'].duplicated().sum()

np.int64(0)

In [36]:
transactions.head()

,transaction_id,worker_id,date_id,channel_id,market_id,transaction_type,amount_local,amount_usd,transaction_outcome,is_fraud_flagged,is_disputed,is_reversed,velocity_score,fraud_loss_usd,processing_time_ms
0,val_0,val_2266,20241016,val_2,val_2,Wallet Funding via Bank Transfer,488.294656,997.696779,Disputed,False,False,True,630.274365,0.000000,990
1,val_1,val_82,20230425,val_5,val_3,Cross-Border Remittance,27.481444,37.330276,Disputed,False,True,True,526.709370,0.000000,634
2,val_2,val_814,20230126,val_4,val_3,Airtime Top-Up,123.147738,378.346227,Reversed,True,True,True,24.060746,3.709239,354
3,val_3,val_566,20231009,val_1,val_3,Wallet Funding via Card,728.374566,239.336698,Declined,True,False,False,132.885522,235.966500,821
4,val_4,val_2117,20230908,val_2,val_0,Refund,686.099797,677.044690,Reversed,True,True,False,446.069701,823.546442,32

In [37]:
transactions.dtypes

transaction_id             str
worker_id                  str
date_id                  int64
channel_id                 str
market_id                  str
transaction_type           str
amount_local           float64
amount_usd             float64
transaction_outcome        str
is_fraud_flagged          bool
is_disputed               bool
is_reversed               bool
velocity_score         float64
fraud_loss_usd         float64
processing_time_ms       int64
dtype: object

In [38]:
transactions.isnull().sum()

transaction_id         0
worker_id              0
date_id                0
channel_id             0
market_id              0
transaction_type       0
amount_local           0
amount_usd             0
transaction_outcome    0
is_fraud_flagged       0
is_disputed            0
is_reversed            0
velocity_score         0
fraud_loss_usd         0
processing_time_ms     0
dtype: int64

In [39]:
transactions.duplicated().sum()

np.int64(0)

In [79]:
dates=pd.read_csv('../data/clean_data/dim_date_updated_cleaned.csv')

In [90]:
df=transactions.merge(
    dates,
    on='date_id',
    how="left"
)


df=df.merge(
    worker,
    on='worker_id',
    how="left"
)


df=df.merge(
    channel,
    on='channel_id',
    how="left"
)

df=df.merge(
    market,
    on='market_id',
    how="left"
)

In [91]:
print(df.head(20))

   transaction_id worker_id   date_id channel_id market_id  \
0           val_0  val_2266  20241016      val_2     val_2
1           val_1    val_82  20230425      val_5     val_3
2           val_2   val_814  20230126      val_4     val_3
3           val_3   val_566  20231009      val_1     val_3
4           val_4  val_2117  20230908      val_2     val_0
5           val_5  val_1311  20230817      val_6     val_0
6           val_6  val_1662  20230523      val_7     val_0
7           val_7  val_3828  20230415      val_1     val_2
8           val_8  val_3414  20241123      val_8     val_1
9           val_9  val_3989  20240712      val_4     val_0
10         val_10  val_4079  20230331     val_11     val_1
11         val_11  val_1240  20240827     val_11     val_2
12         val_12  val_3078  20240308      val_7     val_0
13         val_13  val_4348  20230202      val_0     val_3
14         val_14  val_1523  20230131      val_1     val_1
15         val_15  val_1878  20230406      val_3     val_0
16         val_16  val_2657  20230812      val_5     val_1
17         val_17  val_3990  20230827      val_4     val_1
18         val_18   val_736  20240601      val_9     val_3
19         val_19  val_2334  20240908      val_7     val_0

                    transaction_type  amount_local  amount_usd  \
0   Wallet Funding via Bank Transfer    488.294656  997.696779
1            Cross-Border Remittance     27.481444   37.330276
2                     Airtime Top-Up    123.147738  378.346227
3            Wallet Funding via Card    728.374566  239.336698
4                             Refund    686.099797  677.044690
5                   Agent Withdrawal    357.204619  765.487332
6            Cross-Border Remittance    451.042080  715.993394
7                      Peer Transfer    538.508960  526.667529
8            Wallet Funding via Card     88.150609  544.099359
9                           Cash-Out    791.138207  118.087295
10           Wallet Funding via Card    220.464934   64.769247
11      Salary/Earnings Disbursement    147.623583  798.972047
12           Cross-Border Remittance    243.273115  537.492491
13      Salary/Earnings Disbursement     43.832197  221.910128
14                          Cash-Out    924.903898  251.761151
15                            Refund    749.640892  595.275474
16                          Reversal    462.363601  194.087500
17                     Peer Transfer    647.398779  264.230606
18                  Agent Withdrawal    942.357246  159.862953
19           Wallet Funding via Card    545.789725  802.059573

    transaction_outcome  is_fraud_flagged  ...  is_digital  avg_fraud_rate  \
0              Disputed             False  ...        True      559.808651
1              Disputed             False  ...        True      701.824799
2              Reversed              True  ...       False      689.533128
3              Declined              True  ...        True      624.746093
4              Reversed              True  ...        True      559.808651
5              Disputed              True  ...        True      599.457503
6             Completed             False  ...       False      448.941414
7              Declined              True  ...        True      624.746093
8              Declined              True  ...       False      675.363542
9                Failed             False  ...       False      689.533128
10             Disputed              True  ...       False      519.299858
11            Completed             False  ...       False      519.299858
12             Reversed             False  ...       False      448.941414
13              Timeout             False  ...        True      857.610585
14  Partially Completed             False  ...        True      624.746093
15              Timeout              True  ...        True      509.099903
16             Declined              True  ...        True      701.824799
17              Pending              True  ...       False      689.533128
18               Failed              True  ...       False      156.684169
19             Disputed             False  ...       False      448.941414

    requires_internet       country  iso_code local_currency  \
0               False         Ghana        GH            GHS
1               False  South Africa        ZA            ZAR
2                True  South Africa        ZA            ZAR
3               False  South Africa        ZA            ZAR
4               False       Nigeria        NG            NGN
5               False       Nigeria        NG            NGN
6               False       Nigeria        NG            NGN
7               False         Ghana        GH            GHS
8               False         Kenya        KE            KES
9                True       Nigeria        NG            NGN
10               True         Kenya        KE            KES
11               True         Ghana        GH            GHS
12              False       Nigeria        NG            NGN
13               True  South Africa        ZA            ZAR
14              False         Kenya        KE            KES
15              False       Nigeria        NG            NGN
16              False         Kenya        KE            KES
17               True         Kenya        KE            KES
18               True  South Africa        ZA            ZAR
19              False       Nigeria        NG            NGN

      dominant_channel    regulatory_tier usd_fx_rate market_fraud_index
0        Bank Transfer    Mature (Tier 1)  872.420701         421.603210
1   Mobile Money Agent    Mature (Tier 1)  354.436281         797.512131
2   Mobile Money Agent    Mature (Tier 1)  354.436281         797.512131
3   Mobile Money Agent    Mature (Tier 1)  354.436281         797.512131
4   Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
5   Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
6   Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
7        Bank Transfer    Mature (Tier 1)  872.420701         421.603210
8           Mobile App    Mature (Tier 1)  366.077978         267.522034
9   Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
10          Mobile App    Mature (Tier 1)  366.077978         267.522034
11       Bank Transfer    Mature (Tier 1)  872.420701         421.603210
12  Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
13  Mobile Money Agent    Mature (Tier 1)  354.436281         797.512131
14          Mobile App    Mature (Tier 1)  366.077978         267.522034
15  Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248
16          Mobile App    Mature (Tier 1)  366.077978         267.522034
17          Mobile App    Mature (Tier 1)  366.077978         267.522034
18  Mobile Money Agent    Mature (Tier 1)  354.436281         797.512131
19  Mobile Money Agent  Emerging (Tier 3)   80.233076         392.846248

[20 rows x 44 columns]

In [92]:
df.columns

Index(['transaction_id', 'worker_id', 'date_id', 'channel_id', 'market_id',
       'transaction_type', 'amount_local', 'amount_usd', 'transaction_outcome',
       'is_fraud_flagged', 'is_disputed', 'is_reversed', 'velocity_score',
       'fraud_loss_usd', 'processing_time_ms', 'full_date', 'year', 'month',
       'quarter', 'day_of_week', 'is_weekend', 'is_month_end', 'week_number',
       'worker_name', 'gig_segment', 'account_tenure_days', 'kyc_tier',
       'gender', 'age_band', 'risk_score', 'is_active', 'preferred_channel',
       'channel_type', 'channel_subtype', 'is_digital', 'avg_fraud_rate',
       'requires_internet', 'country', 'iso_code', 'local_currency',
       'dominant_channel', 'regulatory_tier', 'usd_fx_rate',
       'market_fraud_index'],
      dtype='str')

In [93]:
df.isnull().sum()

transaction_id         0
worker_id              0
date_id                0
channel_id             0
market_id              0
transaction_type       0
amount_local           0
amount_usd             0
transaction_outcome    0
is_fraud_flagged       0
is_disputed            0
is_reversed            0
velocity_score         0
fraud_loss_usd         0
processing_time_ms     0
full_date              0
year                   0
month                  0
quarter                0
day_of_week            0
is_weekend             0
is_month_end           0
week_number            0
worker_name            0
gig_segment            0
account_tenure_days    0
kyc_tier               0
gender                 0
age_band               0
risk_score             0
is_active              0
preferred_channel      0
channel_type           0
channel_subtype        0
is_digital             0
avg_fraud_rate         0
requires_internet      0
country                0
iso_code               0
local_currency         0
dominant_channel       0
regulatory_tier        0
usd_fx_rate            0
market_fraud_index     0
dtype: int64

In [94]:
df.duplicated().sum()

np.int64(0)

In [95]:
df.dtypes

transaction_id             str
worker_id                  str
date_id                  int64
channel_id                 str
market_id                  str
transaction_type           str
amount_local           float64
amount_usd             float64
transaction_outcome        str
is_fraud_flagged          bool
is_disputed               bool
is_reversed               bool
velocity_score         float64
fraud_loss_usd         float64
processing_time_ms       int64
full_date                  str
year                     int64
month                      str
quarter                    str
day_of_week                str
is_weekend                bool
is_month_end              bool
week_number              int64
worker_name                str
gig_segment                str
account_tenure_days      int64
kyc_tier                   str
gender                     str
age_band                   str
risk_score             float64
is_active                 bool
preferred_channel          str
channel_type               str
channel_subtype            str
is_digital                bool
avg_fraud_rate         float64
requires_internet         bool
country                    str
iso_code                   str
local_currency             str
dominant_channel           str
regulatory_tier            str
usd_fx_rate            float64
market_fraud_index     float64
dtype: object

In [96]:
df['full_date']=pd.to_datetime(df['full_date'])

In [102]:
df.dtypes

transaction_id                    str
worker_id                         str
date_id                         int64
channel_id                        str
market_id                         str
transaction_type                  str
amount_local                  float64
amount_usd                    float64
transaction_outcome               str
is_fraud_flagged                 bool
is_disputed                      bool
is_reversed                      bool
velocity_score                float64
fraud_loss_usd                float64
processing_time_ms              int64
full_date              datetime64[us]
year                            int64
month                             str
quarter                           str
day_of_week                       str
is_weekend                       bool
is_month_end                     bool
week_number                     int64
worker_name                       str
gig_segment                       str
account_tenure_days             int64
kyc_tier                          str
gender                            str
age_band                          str
risk_score                    float64
is_active                        bool
preferred_channel                 str
channel_type                      str
channel_subtype                   str
is_digital                       bool
avg_fraud_rate                float64
requires_internet                bool
country                           str
iso_code                          str
local_currency                    str
dominant_channel                  str
regulatory_tier                   str
usd_fx_rate                   float64
market_fraud_index            float64
dtype: object

In [103]:
df.to_csv("../data/merged_table_data/merged_table.csv",index=False)